2025-05-28 19:17:15.778 +03:30 [INF] سرویس Outbox Dispatcher شروع به کار کرد
2025-05-28 19:17:16.121 +03:30 [WRN] Entity 'Organization' has a global query filter defined and is the required end of a relationship with the entity 'AuditLog'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2025-05-28 19:17:16.124 +03:30 [WRN] Entity 'Organization' has a global query filter defined and is the required end of a relationship with the entity 'InboxEvent'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2025-05-28 19:17:16.126 +03:30 [WRN] Entity 'Organization' has a global query filter defined and is the required end of a relationship with the entity 'OutboxEvent'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2025-05-28 19:17:16.127 +03:30 [WRN] Entity 'PermissionGroup' has a global query filter defined and is the required end of a relationship with the entity 'RolePermissionGroup'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2025-05-28 19:17:16.128 +03:30 [WRN] Entity 'Role' has a global query filter defined and is the required end of a relationship with the entity 'UserRole'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2025-05-28 19:17:16.251 +03:30 [INF] Exchange ها و Queue های RabbitMQ ایجاد شدند
2025-05-28 19:17:16.492 +03:30 [INF] سرویس Inbox Processor شروع به کار کرد
2025-05-28 19:17:16.501 +03:30 [INF] Consumer برای صف lendtech.user.events با تگ amq.ctag-00ebymsNeetmiRprCcW0Cg ثبت شد
2025-05-28 19:17:16.503 +03:30 [INF] Consumer برای صف lendtech.organization.events با تگ amq.ctag-tKa1APYhVGxOi-4U4N_E0w ثبت شد
2025-05-28 19:17:16.507 +03:30 [INF] Consumer برای صف lendtech.financial.events با تگ amq.ctag-f1JGHynjExZ6zsJalNkVpQ ثبت شد
2025-05-28 19:17:16.508 +03:30 [INF] Consumer ها برای صف‌های پیام ثبت شدند
2025-05-28 19:17:16.509 +03:30 [INF] سرویس Cache Refresh شروع به کار کرد
2025-05-28 19:17:16.546 +03:30 [INF] سرویس Cleanup شروع به کار کرد با زمان‌بندی: 0 2 * * *
2025-05-28 19:17:16.549 +03:30 [INF] اجرای بعدی Cleanup در: "2025-05-29T02:00:00.0000000Z"
2025-05-28 19:17:16.580 +03:30 [INF] Initializing UI Database
2025-05-28 19:17:16.635 +03:30 [ERR] Failed executing DbCommand (69ms) [Parameters=[@__p_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT TOP(@__p_0) [o].[Id], [o].[CreatedAt], [o].[CreatedBy], [o].[EventData], [o].[EventType], [o].[ModifiedAt], [o].[ModifiedBy], [o].[OrganizationId], [o].[ProcessedAt], [o].[RetryCount]
FROM [OutboxEvents] AS [o]
WHERE [o].[ProcessedAt] IS NULL
ORDER BY [o].[CreatedAt]
2025-05-28 19:17:16.640 +03:30 [INF] کش 0 سازمان به‌روزرسانی شد
2025-05-28 19:17:16.646 +03:30 [ERR] An exception occurred while iterating over the results of a query for context type 'LendTech.Database.LendTechDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:b4cb1769-7065-4eb3-8757-b1a5ba758565
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:b4cb1769-7065-4eb3-8757-b1a5ba758565
Error Number:207,State:1,Class:16
2025-05-28 19:17:16.648 +03:30 [INF] کش 0 نرخ ارز به‌روزرسانی شد
2025-05-28 19:17:16.771 +03:30 [ERR] خطای غیرمنتظره در Outbox Dispatcher
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at LendTech.Infrastructure.Repositories.OutboxEventRepository.GetUnprocessedEventsAsync(Int32 batchSize, CancellationToken cancellationToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.Infrastructure\Repositories\OutboxEventRepository.cs:line 26
   at LendTech.BackgroundTasks.Services.OutboxDispatcherService.ProcessOutboxEvents(CancellationToken cancellationToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.BackgroundTasks\Services\OutboxDispatcherService.cs:line 84
   at LendTech.BackgroundTasks.Services.OutboxDispatcherService.ExecuteAsync(CancellationToken stoppingToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.BackgroundTasks\Services\OutboxDispatcherService.cs:line 54
ClientConnectionId:b4cb1769-7065-4eb3-8757-b1a5ba758565
Error Number:207,State:1,Class:16
2025-05-28 19:17:16.786 +03:30 [INF] کش دسترسی‌های 0 کاربر فعال به‌روزرسانی شد
2025-05-28 19:17:16.798 +03:30 [INF] Saving healthchecks configuration to database
2025-05-28 19:17:17.399 +03:30 [INF] HTTP GET /health responded 200 in 282.1236 ms
2025-05-28 19:17:46.800 +03:30 [ERR] Failed executing DbCommand (2ms) [Parameters=[@__p_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT TOP(@__p_0) [o].[Id], [o].[CreatedAt], [o].[CreatedBy], [o].[EventData], [o].[EventType], [o].[ModifiedAt], [o].[ModifiedBy], [o].[OrganizationId], [o].[ProcessedAt], [o].[RetryCount]
FROM [OutboxEvents] AS [o]
WHERE [o].[ProcessedAt] IS NULL
ORDER BY [o].[CreatedAt]
2025-05-28 19:17:46.802 +03:30 [ERR] An exception occurred while iterating over the results of a query for context type 'LendTech.Database.LendTechDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:6f1ea8f5-3c76-44e1-a036-d8dca66fc34d
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:6f1ea8f5-3c76-44e1-a036-d8dca66fc34d
Error Number:207,State:1,Class:16
2025-05-28 19:17:46.881 +03:30 [ERR] خطای غیرمنتظره در Outbox Dispatcher
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at LendTech.Infrastructure.Repositories.OutboxEventRepository.GetUnprocessedEventsAsync(Int32 batchSize, CancellationToken cancellationToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.Infrastructure\Repositories\OutboxEventRepository.cs:line 26
   at LendTech.BackgroundTasks.Services.OutboxDispatcherService.ProcessOutboxEvents(CancellationToken cancellationToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.BackgroundTasks\Services\OutboxDispatcherService.cs:line 84
   at LendTech.BackgroundTasks.Services.OutboxDispatcherService.ExecuteAsync(CancellationToken stoppingToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.BackgroundTasks\Services\OutboxDispatcherService.cs:line 54
ClientConnectionId:6f1ea8f5-3c76-44e1-a036-d8dca66fc34d
Error Number:207,State:1,Class:16
2025-05-28 19:17:47.624 +03:30 [INF] HTTP GET /health responded 200 in 5.5962 ms
2025-05-28 19:17:54.065 +03:30 [WRN] کاربر فاقد شناسه معتبر است
2025-05-28 19:17:54.069 +03:30 [INF] HTTP GET /api/v1/Users responded 401 in 8.7945 ms
2025-05-28 19:18:08.594 +03:30 [INF] شروع پردازش درخواست LoginCommand f48474cc-bb70-478d-87ed-236621910733 {"LoginRequest":{"Username":"dsfsdf","Password":"sdfsdf","OrganizationId":"3fa85f64-5717-4562-b3fc-2c963f66afa6","RememberMe":true,"$type":"LoginRequestDto"},"IpAddress":"127.0.0.1","UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0","$type":"LoginCommand"}
2025-05-28 19:18:08.620 +03:30 [ERR] خطا در پردازش درخواست LoginCommand f48474cc-bb70-478d-87ed-236621910733 پس از 20ms
System.InvalidOperationException: No service for type 'MediatR.IRequestHandler`2[LendTech.Application.Commands.Auth.LoginCommand,Ardalis.Result.Result`1[LendTech.Application.DTOs.Auth.LoginResponseDto]]' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at MediatR.Wrappers.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.<Handle>g__Handler|0()
   at LendTech.Application.Behaviors.LoggingBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.Application\Behaviors\LoggingBehavior.cs:line 32
2025-05-28 19:18:13.930 +03:30 [ERR] خطای ناشناخته رخ داده است
System.InvalidOperationException: No service for type 'MediatR.IRequestHandler`2[LendTech.Application.Commands.Auth.LoginCommand,Ardalis.Result.Result`1[LendTech.Application.DTOs.Auth.LoginResponseDto]]' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at MediatR.Wrappers.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.<Handle>g__Handler|0()
   at LendTech.Application.Behaviors.LoggingBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.Application\Behaviors\LoggingBehavior.cs:line 32
   at LendTech.Application.Behaviors.ValidationBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.Application\Behaviors\ValidationBehavior.cs:line 25
   at LendTech.API.Controllers.AuthController.Login(LoginRequestDto request) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.API\Controllers\AuthController.cs:line 45
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RateLimiting.RateLimitingMiddleware.InvokeInternal(HttpContext context, EnableRateLimitingAttribute enableRateLimitingAttribute)
   at LendTech.API.Middleware.GlobalExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.API\Middleware\GlobalExceptionHandlerMiddleware.cs:line 28
2025-05-28 19:18:13.941 +03:30 [ERR] HTTP POST /api/v1/Auth/login responded 500 in 5412.5821 ms
2025-05-28 19:18:16.901 +03:30 [ERR] Failed executing DbCommand (1ms) [Parameters=[@__p_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT TOP(@__p_0) [o].[Id], [o].[CreatedAt], [o].[CreatedBy], [o].[EventData], [o].[EventType], [o].[ModifiedAt], [o].[ModifiedBy], [o].[OrganizationId], [o].[ProcessedAt], [o].[RetryCount]
FROM [OutboxEvents] AS [o]
WHERE [o].[ProcessedAt] IS NULL
ORDER BY [o].[CreatedAt]
2025-05-28 19:18:16.903 +03:30 [ERR] An exception occurred while iterating over the results of a query for context type 'LendTech.Database.LendTechDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:6f1ea8f5-3c76-44e1-a036-d8dca66fc34d
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:6f1ea8f5-3c76-44e1-a036-d8dca66fc34d
Error Number:207,State:1,Class:16
2025-05-28 19:18:16.973 +03:30 [ERR] خطای غیرمنتظره در Outbox Dispatcher
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at LendTech.Infrastructure.Repositories.OutboxEventRepository.GetUnprocessedEventsAsync(Int32 batchSize, CancellationToken cancellationToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.Infrastructure\Repositories\OutboxEventRepository.cs:line 26
   at LendTech.BackgroundTasks.Services.OutboxDispatcherService.ProcessOutboxEvents(CancellationToken cancellationToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.BackgroundTasks\Services\OutboxDispatcherService.cs:line 84
   at LendTech.BackgroundTasks.Services.OutboxDispatcherService.ExecuteAsync(CancellationToken stoppingToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.BackgroundTasks\Services\OutboxDispatcherService.cs:line 54
ClientConnectionId:6f1ea8f5-3c76-44e1-a036-d8dca66fc34d
Error Number:207,State:1,Class:16
2025-05-28 19:18:17.688 +03:30 [INF] HTTP GET /health responded 200 in 27.0523 ms
2025-05-28 19:18:50.146 +03:30 [INF] شروع راه‌اندازی سرویس LendTech API
2025-05-28 19:18:50.954 +03:30 [INF] سرویس Outbox Dispatcher شروع به کار کرد
2025-05-28 19:18:51.291 +03:30 [WRN] Entity 'Organization' has a global query filter defined and is the required end of a relationship with the entity 'AuditLog'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2025-05-28 19:18:51.293 +03:30 [WRN] Entity 'Organization' has a global query filter defined and is the required end of a relationship with the entity 'InboxEvent'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2025-05-28 19:18:51.294 +03:30 [WRN] Entity 'Organization' has a global query filter defined and is the required end of a relationship with the entity 'OutboxEvent'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2025-05-28 19:18:51.296 +03:30 [WRN] Entity 'PermissionGroup' has a global query filter defined and is the required end of a relationship with the entity 'RolePermissionGroup'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2025-05-28 19:18:51.297 +03:30 [WRN] Entity 'Role' has a global query filter defined and is the required end of a relationship with the entity 'UserRole'. This may lead to unexpected results when the required entity is filtered out. Either configure the navigation as optional, or define matching query filters for both entities in the navigation. See https://go.microsoft.com/fwlink/?linkid=2131316 for more information.
2025-05-28 19:18:51.430 +03:30 [INF] Exchange ها و Queue های RabbitMQ ایجاد شدند
2025-05-28 19:18:51.715 +03:30 [INF] سرویس Inbox Processor شروع به کار کرد
2025-05-28 19:18:51.723 +03:30 [INF] Consumer برای صف lendtech.user.events با تگ amq.ctag-VgWRIUv2A-_dZAiSKgVHHQ ثبت شد
2025-05-28 19:18:51.762 +03:30 [INF] Consumer برای صف lendtech.organization.events با تگ amq.ctag-4L3ebpuQZDr4y5bmvFgetg ثبت شد
2025-05-28 19:18:51.763 +03:30 [INF] Consumer برای صف lendtech.financial.events با تگ amq.ctag-x_U4ay3l4-InroDWj7Jq4A ثبت شد
2025-05-28 19:18:51.765 +03:30 [INF] Consumer ها برای صف‌های پیام ثبت شدند
2025-05-28 19:18:51.766 +03:30 [INF] سرویس Cache Refresh شروع به کار کرد
2025-05-28 19:18:51.806 +03:30 [INF] سرویس Cleanup شروع به کار کرد با زمان‌بندی: 0 2 * * *
2025-05-28 19:18:51.808 +03:30 [INF] اجرای بعدی Cleanup در: "2025-05-29T02:00:00.0000000Z"
2025-05-28 19:18:51.901 +03:30 [ERR] Failed executing DbCommand (110ms) [Parameters=[@__p_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT TOP(@__p_0) [o].[Id], [o].[CreatedAt], [o].[CreatedBy], [o].[EventData], [o].[EventType], [o].[ModifiedAt], [o].[ModifiedBy], [o].[OrganizationId], [o].[ProcessedAt], [o].[RetryCount]
FROM [OutboxEvents] AS [o]
WHERE [o].[ProcessedAt] IS NULL
ORDER BY [o].[CreatedAt]
2025-05-28 19:18:51.904 +03:30 [INF] Initializing UI Database
2025-05-28 19:18:51.910 +03:30 [INF] کش 0 سازمان به‌روزرسانی شد
2025-05-28 19:18:51.916 +03:30 [ERR] An exception occurred while iterating over the results of a query for context type 'LendTech.Database.LendTechDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:791e65d6-167f-4d91-8e2b-67a5906cc59b
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:791e65d6-167f-4d91-8e2b-67a5906cc59b
Error Number:207,State:1,Class:16
2025-05-28 19:18:51.918 +03:30 [INF] کش 0 نرخ ارز به‌روزرسانی شد
2025-05-28 19:18:52.013 +03:30 [ERR] خطای غیرمنتظره در Outbox Dispatcher
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at LendTech.Infrastructure.Repositories.OutboxEventRepository.GetUnprocessedEventsAsync(Int32 batchSize, CancellationToken cancellationToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.Infrastructure\Repositories\OutboxEventRepository.cs:line 26
   at LendTech.BackgroundTasks.Services.OutboxDispatcherService.ProcessOutboxEvents(CancellationToken cancellationToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.BackgroundTasks\Services\OutboxDispatcherService.cs:line 84
   at LendTech.BackgroundTasks.Services.OutboxDispatcherService.ExecuteAsync(CancellationToken stoppingToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.BackgroundTasks\Services\OutboxDispatcherService.cs:line 54
ClientConnectionId:791e65d6-167f-4d91-8e2b-67a5906cc59b
Error Number:207,State:1,Class:16
2025-05-28 19:18:52.029 +03:30 [INF] کش دسترسی‌های 0 کاربر فعال به‌روزرسانی شد
2025-05-28 19:18:52.057 +03:30 [INF] Saving healthchecks configuration to database
2025-05-28 19:18:52.625 +03:30 [INF] HTTP GET /health responded 200 in 272.8742 ms
2025-05-28 19:19:22.038 +03:30 [ERR] Failed executing DbCommand (2ms) [Parameters=[@__p_0='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SELECT TOP(@__p_0) [o].[Id], [o].[CreatedAt], [o].[CreatedBy], [o].[EventData], [o].[EventType], [o].[ModifiedAt], [o].[ModifiedBy], [o].[OrganizationId], [o].[ProcessedAt], [o].[RetryCount]
FROM [OutboxEvents] AS [o]
WHERE [o].[ProcessedAt] IS NULL
ORDER BY [o].[CreatedAt]
2025-05-28 19:19:22.041 +03:30 [ERR] An exception occurred while iterating over the results of a query for context type 'LendTech.Database.LendTechDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:791e65d6-167f-4d91-8e2b-67a5906cc59b
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:791e65d6-167f-4d91-8e2b-67a5906cc59b
Error Number:207,State:1,Class:16
2025-05-28 19:19:22.125 +03:30 [ERR] خطای غیرمنتظره در Outbox Dispatcher
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedBy'.
Invalid column name 'ModifiedAt'.
Invalid column name 'ModifiedBy'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at LendTech.Infrastructure.Repositories.OutboxEventRepository.GetUnprocessedEventsAsync(Int32 batchSize, CancellationToken cancellationToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.Infrastructure\Repositories\OutboxEventRepository.cs:line 26
   at LendTech.BackgroundTasks.Services.OutboxDispatcherService.ProcessOutboxEvents(CancellationToken cancellationToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.BackgroundTasks\Services\OutboxDispatcherService.cs:line 84
   at LendTech.BackgroundTasks.Services.OutboxDispatcherService.ExecuteAsync(CancellationToken stoppingToken) in D:\Project\Fantap\GitHub\Cqrs\Cqrs\LendTech.BackgroundTasks\Services\OutboxDispatcherService.cs:line 54
ClientConnectionId:791e65d6-167f-4d91-8e2b-67a5906cc59b
Error Number:207,State:1,Class:16
2025-05-28 19:19:22.777 +03:30 [INF] HTTP GET /health responded 200 in 2.2744 ms
